Map musics = {
  0: {
    'name': 'Inferno',
    'youtubeid': 'wfCcs0vLysk',
    'BPM': 185,
    'beatability': 0.7,
    'genre': 'j-rock',
    'artist': 'Mrs. GREEN APPLE',
  },
  1: {
    'name': 'WanteD WanteD',
    'youtubeid': 'PbISczErpKY',
    'BPM': 160,
    'beatability': 0.8,
    'genre': 'j-rock',
    'artist': 'Mrs. GREEN APPLE',
  },
  2: {
    'name': '青と夏 ',
    'youtubeid': 'm34DPnRUfMU',
    'BPM': 185,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': 'Mrs. GREEN APPLE',
  },
  3: {
    'name': 'アゲイン ',
    'youtubeid': 'kHHUulGxZww',
    'BPM': 195,
    'beatability': 0.3,
    'genre': 'j-rock',
    'artist': 'WANIMA',
  },
  4: {
    'name': 'ともに',
    'youtubeid': 'qag4ewos4TE',
    'BPM': 127,
    'beatability': 0.6,
    'genre': 'j-rock',
    'artist': 'WANIMA',
  },
  5: {
    'name': 'やってみよう',
    'youtubeid': 'wdbW5Oqen44',
    'BPM': 129.5,
    'beatability': 0.6,
    'genre': 'j-rock',
    'artist': 'WANIMA',
  },
  6: {
    'name': 'おやすみグッドナイト ',
    'youtubeid': '67pc-YzEW_I',
    'BPM': 138,
    'beatability': 0.4,
    'genre': 'j-rock',
    'artist': 'ステレオガール',
  },
  7: {
    'name': 'You',
    'youtubeid': 'sA_p0rQtDXE',
    'BPM': 128,
    'beatability': 0.3,
    'genre': 'edm',
    'artist': 'Axol lAlex Skrido',
  },
  8: {
    'name': 'Calling you (Club Edit)',
    'youtubeid': 'L0mrY3c3inw',
    'BPM': 128,
    'beatability': 0.4,
    'genre': 'edm',
    'artist': 'Stephan F',
  },
  9: {
    'name': 'Higher',
    'youtubeid': 'I-iQrUSmMvk',
    'BPM': 128,
    'beatability': 0.4,
    'genre': 'edm',
    'artist': 'Tubotronic',
  },
  10: {
    'name': 'きらり ',
    'youtubeid': 'TcLLpZBWsck',
    'BPM': 117,
    'beatability': 0.3,
    'genre': 'r&b/soul',
    'artist': '藤井風',
  },
  11: {
    'name': 'BOY',
    'youtubeid': 'n0QNaym0jDI',
    'BPM': 110,
    'beatability': 0.2,
    'genre': 'j-pop',
    'artist': 'King Gnu',
  },
  12: {
    'name': 'ミュージック ',
    'youtubeid': 'z2TNnnQbGJs',
    'BPM': 136,
    'beatability': 0.1,
    'genre': 'techno',
    'artist': 'サカナクション',
  },
  13: {
    'name': '踊り子 ',
    'youtubeid': '7HgJIAUtICU',
    'BPM': 157,
    'beatability': 0.3,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  14: {
    'name': 'Panorama ',
    'youtubeid': 'Yfa41yK7-9g',
    'BPM': 126,
    'beatability': 0.2,
    'genre': 'k-pop',
    'artist': 'IZONE',
  },
  15: {
    'name': 'Mela! ',
    'youtubeid': 'aRDURmIYBZ4',
    'BPM': 138,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': '緑黄色社会',
  },
  16: {
    'name': '三原色 ',
    'youtubeid': 'nhOhFOoURnE',
    'BPM': 128,
    'beatability': 0,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  17: {
    'name': 'AS IF ITS YOUR LAST ',
    'youtubeid': 'Amq-qlqbjYA',
    'BPM': 125,
    'beatability': 0.3,
    'genre': 'k-pop',
    'artist': 'BLACKPINK',
  },
  18: {
    'name': '1mm',
    'youtubeid': 'JF4JUQ4WnXg',
    'BPM': 93,
    'beatability': 0.7,
    'genre': 'alternative/indies',
    'artist': 'showmore',
  },
  19: {
    'name': 'Naked Men 見ろ、裸の俺たちを! ',
    'youtubeid': 'yFRMCwn7ass',
    'BPM': 127,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': 'デーモン閣下',
  },
  20: {
    'name': 'Runner ',
    'youtubeid': 'Jtw5S12-ZeI',
    'BPM': 124,
    'beatability': 0.7,
    'genre': 'j-rock',
    'artist': 'サンプラザ中野くん',
  },
  21: {
    'name': 'Despacito',
    'youtubeid': '8wU7WB_ocSU',
    'BPM': 150,
    'beatability': 0.3,
    'genre': 'edm',
    'artist': 'Luis Fonsi',
  },
  22: {
    'name': 'Shape of You',
    'youtubeid': 'JGwWNGJdvx8',
    'BPM': 150,
    'beatability': 0.8,
    'genre': 'techno',
    'artist': 'Ed Sheeran',
  },
  23: {
    'name': 'レーザービーム',
    'youtubeid': 'K54CYowOqxM',
    'BPM': 135.008,
    'beatability': 0.7,
    'genre': 'techno',
    'artist': 'Perfume',
  },
  24: {
    'name': '少女病',
    'youtubeid': '9y-T1DuNuSY',
    'BPM': 145.064,
    'beatability': 0.3,
    'genre': 'j-rock',
    'artist': 'Philosopher',
  },
  25: {
    'name': 'インフェルノ',
    'youtubeid': '8DizBlRFMD4',
    'BPM': 195.042,
    'beatability': 0.3,
    'genre': 'j-rock',
    'artist': '9mm Parabellum Bullet',
  },
  26: {
    'name': 'サクリファイス',
    'youtubeid': 'CVNy1p3CrVM',
    'BPM': 199.978,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': '9mm Parabellum Bullet',
  },
  27: {
    'name': 'Atarashii Hikari',
    'youtubeid': 'uCrhhsOPav4',
    'BPM': 179.879,
    'beatability': 0.2,
    'genre': 'j-rock',
    'artist': '9mm Parabellum Bullet',
  },
  28: {
    'name': 'Black Market',
    'youtubeid': 'mNFHg5vQ2pU',
    'BPM': 157.955,
    'beatability': 0.6,
    'genre': 'j-rock',
    'artist': '9mm Parabellum Bullet',
  },
  29: {
    'name': 'フルドライブ',
    'youtubeid': 'adK2Fol2SkM',
    'BPM': 177.965,
    'beatability': 0.7,
    'genre': 'j-rock',
    'artist': 'KANA-BOON',
  },
  30: {
    'name': 'Raise your flag ',
    'youtubeid': 'G-UN6uRMBRw',
    'BPM': 144.946,
    'beatability': 0.6,
    'genre': 'alternative/indies',
    'artist': 'MAN WITH A MISSION',
  },
  31: {
    'name': 'コバルトブルー',
    'youtubeid': 'yf_xwI865gg',
    'BPM': 227.256,
    'beatability': 0.6,
    'genre': 'j-rock',
    'artist': 'THE BACK HORN',
  },
  32: {
    'name': '戦う君よ',
    'youtubeid': 'QPdhZR_CIck',
    'BPM': 219.116,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': 'THE BACK HORN',
  },
  33: {
    'name': '罠',
    'youtubeid': '_aw01by-hzE',
    'BPM': 198.047,
    'beatability': 0.4,
    'genre': 'j-rock',
    'artist': 'THE BACK HORN',
  },
  34: {
    'name': 'オンリーワンダー',
    'youtubeid': 'oCrwzN6eb4Q',
    'BPM': 166.662,
    'beatability': 0.6,
    'genre': 'j-pop',
    'artist': 'フレデリック',
  },
  35: {
    'name': 'マチガミ少女',
    'youtubeid': 'wVXE0UseufM',
    'BPM': 197.024,
    'beatability': 0.3,
    'genre': 'j-rock',
    'artist': '仲恵光城',
  },
  36: {
    'name': '刃',
    'youtubeid': '7LmDZyGdCUc',
    'BPM': 151,
    'beatability': 0.4,
    'genre': 'j-rock',
    'artist': 'THE BACK HORN',
  },
  37: {
    'name': '怪獣の花唄',
    'youtubeid': 'UM9XNpgrqVk',
    'BPM': 150,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  38: {
    'name': '不可幸力',
    'youtubeid': 'Gbz2C2gQREI',
    'BPM': 94,
    'beatability': 0.2,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  39: {
    'name': '東京フラッシュ ',
    'youtubeid': 'SIuF37EWaLU',
    'BPM': 98,
    'beatability': 0.7,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  40: {
    'name': '恋風邪にのせて',
    'youtubeid': '1FIhcdocT-k',
    'BPM': 118,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  41: {
    'name': '花占い',
    'youtubeid': 'onhBN0qkUcE',
    'BPM': 135,
    'beatability': 0.4,
    'genre': 'j-pop',
    'artist': 'Vaundy',
  },
  42: {
    'name': 'Overdose',
    'youtubeid': 'H08YWE4CIFQ',
    'BPM': 118,
    'beatability': 0.7,
    'genre': 'j-pop',
    'artist': 'なとり',
  },
  43: {
    'name': 'キャラクター',
    'youtubeid': 'ulforNn47PM',
    'BPM': 124,
    'beatability': 0.7,
    'genre': 'j-pop',
    'artist': '緑黄色社会',
  },
  44: {
    'name': '陽はまた昇るから',
    'youtubeid': 'e5FEOVTRfFc',
    'BPM': 142,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': '緑黄色社会',
  },
  45: {
    'name': 'Say So ',
    'youtubeid': 'uAYG46w1SCA',
    'BPM': 111,
    'beatability': 0.9,
    'genre': 'r&b/soul',
    'artist': 'Doja Cat',
  },
  46: {
    'name': 'Boss Bitch',
    'youtubeid': 'sP7lp8UD1Xw',
    'BPM': 126,
    'beatability': 0.7,
    'genre': 'hip-hop/pop-rap',
    'artist': 'Doja Cat',
  },
  47: {
    'name': 'Like That (feat. Gucci Mane)',
    'youtubeid': 'U5JnPyjQnXY',
    'BPM': 106,
    'beatability': 0.5,
    'genre': 'r&b/soul',
    'artist': 'Doja Cat',
  },
  48: {
    'name': 'STAY',
    'youtubeid': 'kTJczUoc26U',
    'BPM': 170,
    'beatability': 0.7,
    'genre': 'w-pop',
    'artist': 'The Kid LAROI, Justin Bieber',
  },
  49: {
    'name': 'What Do You Mean?',
    'youtubeid': 'DK_0jXPuIr0',
    'BPM': 125,
    'beatability': 0.3,
    'genre': 'w-pop',
    'artist': 'Justin Bieber',
  },
  50: {
    'name': 'Baby ft. Ludacris',
    'youtubeid': 'kffacxfA7G4',
    'BPM': 130,
    'beatability': 0.4,
    'genre': 'w-pop',
    'artist': 'Justin Bieber',
  },
  51: {
    'name': 'Uptown Funk (feat. Bruno Mars)',
    'youtubeid': 'OPf0YbXqDm0',
    'BPM': 115,
    'beatability': 0.9,
    'genre': 'funk',
    'artist': 'Mark Ronson ',
  },
  52: {
    'name': 'ミックスナッツ',
    'youtubeid': 'CbH2F0kXgTY',
    'BPM': 150,
    'beatability': 0.4,
    'genre': 'j-pop',
    'artist': 'Official髭男dism',
  },
  53: {
    'name': 'Pretender',
    'youtubeid': 'TQ8WlA2GXbk',
    'BPM': 92,
    'beatability': 0.1,
    'genre': 'j-pop',
    'artist': 'Official髭男dism',
  },
  54: {
    'name': 'Cry Baby',
    'youtubeid': 'O1bhZgkC4Gw',
    'BPM': 100,
    'beatability': 0.4,
    'genre': 'alternative/indies',
    'artist': 'Official髭男dism',
  },
  55: {
    'name': 'ノーダウト',
    'youtubeid': 'EHw005ZqCXk',
    'BPM': 150,
    'beatability': 0.4,
    'genre': 'r&b/soul',
    'artist': 'Official髭男dism',
  },
  56: {
    'name': '宿命',
    'youtubeid': '-kgOFJG881I',
    'BPM': 82,
    'beatability': 0.1,
    'genre': 'j-pop',
    'artist': 'Official髭男dism',
  },
  57: {
    'name': 'イエスタデイ',
    'youtubeid': 'DuMqFknYHBs',
    'BPM': 130,
    'beatability': 0.6,
    'genre': 'j-pop',
    'artist': 'Official髭男dism',
  },
  58: {
    'name': 'FIRE GROUND',
    'youtubeid': 'sem3UU-EQJs',
    'BPM': 114,
    'beatability': 0.8,
    'genre': 'alternative/indies',
    'artist': 'Official髭男dism',
  },
  59: {
    'name': 'Stand By You',
    'youtubeid': '22mOCjkwQjM',
    'BPM': 154,
    'beatability': 0.5,
    'genre': 'r&b/soul',
    'artist': 'Official髭男dism',
  },
  60: {
    'name': '115万キロのフィルム',
    'youtubeid': 'ljDRzQz3ULE',
    'BPM': 97,
    'beatability': 0.6,
    'genre': 'j-pop',
    'artist': 'Official髭男dism',
  },
  61: {
    'name': '怪物',
    'youtubeid': 'dy90tA3TT1c',
    'BPM': 170,
    'beatability': 0.6,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  62: {
    'name': '三原色',
    'youtubeid': 'nhOhFOoURnE',
    'BPM': 128,
    'beatability': 0.8,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  63: {
    'name': '群青',
    'youtubeid': 'Y4nEEZwckuU',
    'BPM': 135,
    'beatability': 0.7,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  64: {
    'name': 'ハルジオン',
    'youtubeid': 'kzdJkT4kp-A',
    'BPM': 130,
    'beatability': 0.6,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  65: {
    'name': 'あの夢をなぞって',
    'youtubeid': 'sAuEeM_6zpk',
    'BPM': 180,
    'beatability': 0.4,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  66: {
    'name': '祝福',
    'youtubeid': '3eytpBOkOFA',
    'BPM': 170,
    'beatability': 0.8,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  67: {
    'name': '夜に駆ける',
    'youtubeid': 'x8VYWazR5mE',
    'BPM': 130,
    'beatability': 0.4,
    'genre': 'j-pop',
    'artist': 'YOASOBI',
  },
  68: {
    'name': 'シネマ feat.初音ミク',
    'youtubeid': 'EEbWRjavSVw',
    'BPM': 124,
    'beatability': 0.6,
    'genre': 'vocaloid',
    'artist': 'Ayase',
  },
  69: {
    'name': '廻廻奇譚',
    'youtubeid': '1tk1pqwrOys',
    'BPM': 185,
    'beatability': 0.5,
    'genre': 'alternative/indies',
    'artist': 'Eve',
  },
  70: {
    'name': 'リライト(2016ver.)',
    'youtubeid': 'bOZixNTn_ck',
    'BPM': 179,
    'beatability': 0.4,
    'genre': 'j-rock',
    'artist': 'ASIAN KUNG-FU GENERATION ',
  },
  71: {
    'name': '明日も',
    'youtubeid': 'zhCtzmDWsN0',
    'BPM': 179,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': 'SHISHAMO',
  },
  72: {
    'name': '前前前世',
    'youtubeid': 'PDSkFeMVNFs',
    'BPM': 190,
    'beatability': 0.5,
    'genre': 'j-rock',
    'artist': 'RADWIMPS',
  },
  73: {
    'name': 'Shake It Off',
    'youtubeid': 'nfWlot6h_JM',
    'BPM': 160,
    'beatability': 0.6,
    'genre': 'w-pop',
    'artist': 'Taylor Swift',
  },
  74: {
    'name': 'NIPPON',
    'youtubeid': '0YF8vecQWYs',
    'BPM': 173,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': '椎名林檎',
  },
  75: {
    'name': '全力少年',
    'youtubeid': 'ZfUgFU6Jf-k',
    'BPM': 134,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': 'スキマスイッチ',
  },
  76: {
    'name': '新宝島',
    'youtubeid': 'LIlZCmETvsY',
    'BPM': 158,
    'beatability': 0.4,
    'genre': 'j-pop',
    'artist': 'サカナクション',
  },
  77: {
    'name': 'Xenogenesis',
    'youtubeid': '2Ax_EIb1zks',
    'BPM': 145,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  78: {
    'name': 'Ascendancy',
    'youtubeid': '77fZT0rldwQ',
    'BPM': 167,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  79: {
    'name': 'Time Lapse',
    'youtubeid': '3fxq7kqyWO8',
    'BPM': 127,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  80: {
    'name': 'Monody (feat. Laura Brehm)',
    'youtubeid': 'B7xai5u_tnk',
    'BPM': 160,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  81: {
    'name': 'Stronger',
    'youtubeid': 'e7KxE95htSM',
    'BPM': 160,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  82: {
    'name': 'Let Love Win',
    'youtubeid': '2tptCDQqIt8',
    'BPM': 148,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  83: {
    'name': 'Kingdom Come',
    'youtubeid': '2tptCDQqIt8',
    'BPM': 172,
    'beatability': 0.5,
    'genre': 'edm',
    'artist': 'TheFatRat',
  },
  84: {
    'name': 'じょいふる',
    'youtubeid': 'viQPExRmxdk',
    'BPM': 159,
    'beatability': 0.8,
    'genre': 'j-pop',
    'artist': 'いきものがかり',
  },
  85: {
    'name': 'うっせぇわ',
    'youtubeid': 'Qp3b-RXtz4w',
    'BPM': 178,
    'beatability': 0.5,
    'genre': 'j-pop',
    'artist': 'Ado',
  },
  86: {
    'name': '阿修羅ちゃん',
    'youtubeid': 'cyq5-StPISU',
    'BPM': 156,
    'beatability': 0.7,
    'genre': 'j-pop',
    'artist': 'Ado',
  },
  87: {
    'name': 'ロストワンの号哭',
    'youtubeid': '8oBV3jPTW4s',
    'BPM': 162,
    'beatability': 0.8,
    'genre': 'vocaloid',
    'artist': 'Neru',
  },
  88: {
    'name': '脱法ロック',
    'youtubeid': 'u5mHVUwDf_0',
    'BPM': 155,
    'beatability': 0.6,
    'genre': 'vocaloid',
    'artist': 'Neru',
  },
  89: {
    'name': 'リモコン',
    'youtubeid': '1st0XSY0VKQ',
    'BPM': 162,
    'beatability': 0.5,
    'genre': 'vocaloid',
    'artist': 'じーざすP',
  },
  90: {
    'name': 'イノコリ先生',
    'youtubeid': 'BkzVOKqTcBo',
    'BPM': 165,
    'beatability': 0.5,
    'genre': 'vocaloid',
    'artist': 'HoneyWorks',
  },
  91: {
    'name': '2way nice guy',
    'youtubeid': 'iZtDuxKztgA',
    'BPM': 130,
    'beatability': 0.7,
    'genre': 'hip-hop/pop-rap',
    'artist': 'Creepy Nuts',
  },
  92: {
    'name': 'よふかしのうた',
    'youtubeid': 'F6_zbnfxoBA',
    'BPM': 115,
    'beatability': 0.4,
    'genre': 'hip-hop/pop-rap',
    'artist': 'Creepy Nuts',
  },
  93: {
    'name': 'Bad Orangez',
    'youtubeid': 'mY3KApEk7zQ',
    'BPM': 180,
    'beatability': 0.5,
    'genre': 'hip-hop/pop-rap',
    'artist': 'Creepy Nuts',
  },
  94: {
    'name': 'Gods Menu',
    'youtubeid': 'TQTlCHxyuu8',
    'BPM': 157,
    'beatability': 0.5,
    'genre': 'k-pop',
    'artist': 'Stray Kids',
  },
  95: {
    'name': 'CASE 143',
    'youtubeid': 'jYSlpC6Ud2A',
    'BPM': 100,
    'beatability': 0.5,
    'genre': 'k-pop',
    'artist': 'Stray Kids',
  },
  96: {
    'name': 'FREEZE',
    'youtubeid': 'etjQd0wgUTo',
    'BPM': 160,
    'beatability': 0.6,
    'genre': 'k-pop',
    'artist': 'Stray Kids',
  },
  97: {
    'name': 'I NEED U',
    'youtubeid': 'jjskoRh8GTE',
    'BPM': 158,
    'beatability': 0.5,
    'genre': 'k-pop',
    'artist': 'BTS',
  },
  98: {
    'name': 'Tamed-Dashed',
    'youtubeid': '6IRsW_TkyVA',
    'BPM': 155,
    'beatability': 0.5,
    'genre': 'k-pop',
    'artist': 'ENHYPEN',
  },
};
