Map musics = {
  0: {
    'name': "インフェルノ",
    'youtubeid' : "wfCcs0vLysk",
    'BPM': 185.0,
    'beatability': 0.6,
    'genre' : "j-rock",
    'artist' : "Mrs. GREEN APPLE",
  },
  1: {
    'name': "Mrs. GREEN APPLE_WanteD WanteD_BPM160",
    'youtubeid' : "PbISczErpKY",
    'BPM': 160.0,
    'beatability': 0.8,
    'genre' : "j-rock",
    'artist' : "Mrs. GREEN APPLE",
  },
  2: {
    'name': "Mrs. GREEN APPLE_青と夏__BPM185",
    'youtubeid' : "m34DPnRUfMU",
    'BPM': 185.0,
    'beatability': 0.5,
    'genre' : "j-rock",
    'artist' : "Mrs. GREEN APPLE",
  },
  3: {
    'name': "WANIMA_アゲイン_BPM195",
    'youtubeid' : "kHHUulGxZww",
    'BPM': 195.0,
    'beatability': 0.3,
    'genre' : "j-rock",
    'artist' : "WANIMA",
  },
  4: {
    'name': "WANIMA_ともに_BPM127",
    'youtubeid' : "qag4ewos4TE",
    'BPM': 127.0,
    'beatability': 0.6,
    'genre' : "j-rock",
    'artist' : "WANIMA",
  },
  5: {
    'name': "WANIMA_やってみよう_BPM129.5",
    'youtubeid' : "wdbW5Oqen44",
    'BPM': 129.5,
    'beatability': 0.6,
    'genre' : "j-rock",
    'artist' : "WANIMA",
  },
  6: {
    'name': "ステレオガール_おやすみグッドナイト_BPM138",
    'youtubeid' : "67pc-YzEW_I",
    'BPM': 138.0,
    'beatability': 0.4,
    'genre' : "j-rock",
    'artist' : "ステレオガール",
  },
  7: {
    'name': "Axol x Alex Skrindo - You [NCS Release]_BPM128",
    'youtubeid' : "sA_p0rQtDXE",
    'BPM': 128.0,
    'beatability': 0.3,
    'genre' : "edm",
    'artist' : "Axol lAlex Skrido",
  },
  8: {
    'name': "Calling You (Club Edit)_BPM128",
    'youtubeid' : "L0mrY3c3inw",
    'BPM': 128.0,
    'beatability': 0.4,
    'genre' : "edm",
    'artist' : "Stephan F",
  },
  9: {
    'name': "Higher (Original Mix)_BPM128",
    'youtubeid' : "I-iQrUSmMvk",
    'BPM': 128.0,
    'beatability': 0.4,
    'genre' : "edm",
    'artist' : "Tubotronic",
  },
  10: {
    'name': "Fujii Kaze - Kirari_BPM117",
    'youtubeid' : "TcLLpZBWsck",
    'BPM': 117.0,
    'beatability': 0.3,
    'genre' : "r&b/soul",
    'artist' : "藤井風",
  },
};